[
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "Recursion exception",
          "type": "System.Exception",
          "stacktrace": "Unknown.lambda_method<scrubbed>"
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "Recursion exception"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "20"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "ExceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "Recursion exception",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "Recursion exception"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "0"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "ExceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": "Unknown.lambda_method<scrubbed>",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "Recursion exception",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "Recursion exception"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "1"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "ExceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": "Unknown.lambda_method<scrubbed>",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "Recursion exception",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "Recursion exception"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "2"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "ExceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": "Unknown.lambda_method<scrubbed>",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "Recursion exception",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.ExceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "Recursion exception"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "3"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "ExceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": "Unknown.lambda_method<scrubbed>",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  }
]