[
  {
    "captures": {
      "entry": {
        "arguments": {},
        "locals": {},
        "staticFields": {}
      },
      "return": {
        "arguments": {
          "this": {
            "type": "com.datadoghq.system_tests.springboot.ExceptionReplayController",
            "fields": {}
          }
        },
        "locals": {},
        "staticFields": {},
        "throwable": {
          "message": "500 INTERNAL_SERVER_ERROR \"Outer exception\"; nested exception is org.springframework.web.server.ResponseStatusException: 500 INTERNAL_SERVER_ERROR \"Inner exception\"",
          "stacktrace": [
            {
              "function": "com.datadoghq.system_tests.springboot.ExceptionReplayController.exceptionReplayInner",
              "lineNumber": 34
            },
            {
              "function": "datadog.trace.instrumentation.springweb.HandlerMappingResourceNameFilter.doFilterInternal",
              "lineNumber": 50
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ],
          "type": "org.springframework.web.server.ResponseStatusException"
        }
      }
    },
    "exceptionId": "<scrubbed>",
    "id": "<scrubbed>",
    "language": "java",
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "lines": [],
        "method": "exceptionReplayInner",
        "type": "com.datadoghq.system_tests.springboot.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "com.datadoghq.system_tests.springboot.ExceptionReplayController.exceptionReplayInner",
        "lineNumber": 34
      },
      {
        "function": "datadog.trace.instrumentation.springweb.HandlerMappingResourceNameFilter.doFilterInternal",
        "lineNumber": 50
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "timestamp": "<scrubbed>"
  }
]