[
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "32"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_inner",
        "lineNumber": 32
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "32": {
          "arguments": {},
          "locals": {
            "ex": {
              "type": "NoneType",
              "isNull": true
            },
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'outer exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_inner",
                "lineNumber": 32
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  }
]