[
  {
    "captures": {
      "entry": {
        "arguments": {},
        "locals": {},
        "staticFields": {}
      },
      "return": {
        "arguments": {},
        "locals": {},
        "staticFields": {},
        "throwable": {
          "message": "500 INTERNAL_SERVER_ERROR \"Async exception\"",
          "stacktrace": [
            {
              "function": "com.datadoghq.system_tests.springboot.ExceptionReplayController.lambda$asyncThrow$0",
              "lineNumber": 75
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ],
          "type": "org.springframework.web.server.ResponseStatusException"
        }
      }
    },
    "exceptionCaptureId": "3b76ee9d-b94a-4729-9b61-99b81cbcb928",
    "exceptionHash": "deebd58eea91f994d019f1d46d8fc725dc437972305579b4c4eb86942c5ac3a8",
    "frameIndex": "0",
    "id": "<scrubbed>",
    "language": "java",
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "lines": [],
        "method": "lambda$asyncThrow$0",
        "type": "com.datadoghq.system_tests.springboot.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "com.datadoghq.system_tests.springboot.ExceptionReplayController.lambda$asyncThrow$0",
        "lineNumber": 75
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "timestamp": "<scrubbed>"
  }
]